restic_backup_folder = "${HOME}/rolling/golang/projects/rsac/tmp/testdata"

[[max_diffs]]
matcher = ".*/user01/.*"
duration = "6h"

[[max_diffs]]
matcher = ".*/user02/repo02.*"
duration = "18h30m"

[[max_diffs]]
matcher = ".*/user03/repo3.*"
duration = "1w"

[[max_diffs]]
matcher = ".*"
duration = "1d"
