restic_backup_folder = "${HOME}/rolling/golang/projects/backup_period_checker/tmp"
default_max_diff = "1d"

# specific_max_diffs
[[smds]]
matcher = "/user001/"
max_diff = "111d"

[[smds]]
matcher = "/user002/"
max_diff = "3d"

[[smds]]
matcher = "/user003/repo3"
max_diff = "3d"
