restic_backup_folder = "${HOME}/rolling/golang/projects/rsac/tmp/testdata"

[max_diffs]
[max_diffs.default_duration]
duration = "1d"

[[max_diffs.specific]]
matcher = ".*/user01/.*"
duration = "6h"

[[max_diffs.specific]]
matcher = ".*/user02/repo02.*"
duration = "3d"

[[max_diffs.specific]]
matcher = ".*/user03/repo3.*"
duration = "3d"
