restic_backup_folder = "${HOME}/rolling/golang/projects/backup_period_checker/tmp"

[max_diffs]
[max_diffs.default_duration]
duration = "1d"

[[max_diffs.specific]]
matcher = "/user001/"
duration = "111d"

[[max_diffs.specific]]
matcher = "/user002/"
duration = "3d"

[[max_diffs.specific]]
matcher = "/user003/repo3"
duration = "3d"
